# Generated by Django 3.2.5 on 2021-07-14 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_alter_category_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='status',
            field=models.CharField(choices=[('P', 'Pending For Approval'), ('R', 'Rejected'), ('A', 'Approved'), ('B', 'Blocked')], default='P', max_length=1, verbose_name='Category Current Status'),
        ),
    ]
