# Generated by Django 3.2.3 on 2021-06-22 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0003_alter_comment_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='commented_by',
            field=models.CharField(default='None', max_length=48),
        ),
        migrations.AlterField(
            model_name='comment',
            name='body',
            field=models.TextField(max_length=1000),
        ),
    ]
