# Generated by Django 3.2.5 on 2021-07-07 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0007_alter_comment_commented_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='dislikes',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='likes',
        ),
    ]
