# Generated by Django 3.2.5 on 2021-07-25 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0008_auto_20210707_1933'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'Comment', 'verbose_name_plural': 'Comments'},
        ),
        migrations.AlterModelTable(
            name='comment',
            table='Comment',
        ),
    ]
