# Generated by Django 3.2.5 on 2021-11-11 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(error_messages={'max_length': "Title cann't be more than 126 characters"}, max_length=250, unique=True, verbose_name='Post Title')),
                ('image', models.URLField(blank=True, default=None, null=True, verbose_name='Post Image URL')),
                ('body', models.TextField(default='None', max_length=5000, verbose_name='Post Description')),
                ('slug', models.SlugField(blank=True, max_length=300, null=True, unique=True, verbose_name='Slug Field')),
                ('published_on', models.DateTimeField(auto_now_add=True, verbose_name='Publication Date')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('status', models.CharField(choices=[('P', 'Pending For Approval'), ('R', 'Rejected'), ('A', 'Approved'), ('B', 'Blocked')], default='P', max_length=1, verbose_name='Post Status')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
                'db_table': 'Post',
            },
        ),
    ]
