# Generated by Django 3.2.3 on 2021-06-24 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_auto_20210624_1858'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='dislike',
            new_name='dislikes',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='like',
            new_name='likes',
        ),
    ]
