# Generated by Django 3.2.5 on 2021-07-14 10:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0004_category_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0014_alter_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('P', 'Pending For Approval'), ('R', 'Rejected'), ('A', 'Approved'), ('B', 'Blocked')], default='P', max_length=1, verbose_name='Post Current Status'),
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Author Username'),
        ),
        migrations.AlterField(
            model_name='post',
            name='body',
            field=models.TextField(default='None', max_length=1000, verbose_name='Post Description'),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ManyToManyField(blank=True, to='category.Category', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='postImages/', verbose_name='Post Image'),
        ),
        migrations.AlterField(
            model_name='post',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Last Updated'),
        ),
        migrations.AlterField(
            model_name='post',
            name='published_on',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Publication Data'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=126, verbose_name='Post Title'),
        ),
    ]
