# Generated by Django 3.2.5 on 2021-09-02 15:54

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0019_alter_post_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body',
            field=ckeditor.fields.RichTextField(default='None', max_length=1000, verbose_name='Post Description'),
        ),
    ]
