# Generated by Django 3.2.5 on 2021-09-03 13:28

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0020_alter_post_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body',
            field=ckeditor.fields.RichTextField(default='None', max_length=5000, verbose_name='Post Description'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(error_messages={'max_length': "Title cann't be more than 126 characters"}, max_length=250, verbose_name='Post Title'),
        ),
    ]
