# Generated by Django 3.2.5 on 2021-10-18 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0022_alter_post_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body',
            field=models.TextField(default='None', max_length=5000, verbose_name='Post Description'),
        ),
    ]
