# Generated by Django 3.2.5 on 2021-10-22 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0023_alter_post_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(error_messages={'max_length': "Title cann't be more than 126 characters"}, max_length=250, unique=True, verbose_name='Post Title'),
        ),
    ]
