# Generated by Django 3.2.5 on 2021-10-24 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0024_alter_post_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.URLField(blank=True, default=None, null=True, verbose_name='Post Image URL'),
        ),
    ]
